### ISSUE TITLE
Unable to sign a message - t.match is not a function

### ISSUE THREAD

**Issue by xyz27900** [tronprotocol/tronwallet-adapter#12]
I tried to sign a message using `@tronweb3/tronwallet-adapters` and TronLink Chrome extension, but got the error:

```
Uncaught (in promise) WalletSignMessageError: t.match is not a function
    at TronLinkAdapter.signMessage (adapter.ts:267:27)
```

Here's the code of my component:

```tsx
export const MyComponent: React.FC = () => {
  const adapter = React.useMemo(() => new TronLinkAdapter(), []);

  const sign = async (msg: string): Promise<string> => {
    const signature = await adapter.signMessage(msg);
    console.log('signature', signature);
    return signature;
  };

  return (
    <div>
      <button onClick={() => adapter.connect()}>Connect</button>
      <button onClick={() => sign("My message")}>Sign Message</button>
    </div>
  );
}
```

When I click the "Sign Message" button after the connection I get the error `t.match is not a function`.

You can even reproduce it by launching the example in the `demos` folder (`demos/react-ui/vite-app` for example).

I guess the cause of the problem is that there's no default privateKey for some reason.

```
TronLink version: V3.27.5
@tronweb3/tronwallet-adapters: 1.1.2
```

**Comment by way2ex** [comment]
Sorry for bringing you inconvenience. 
In Wallet Adapter we use `tronWeb v4.4` and `signMessage` is using `tronWeb.trx.signMessageV2`  instead of `tronWeb.trx.sign` because `tronWeb.trx.sign` can only accept hexString and is not readable.

But  the version of `tronWeb` in TronLink V3.27.5 is `v4.1.0` which doesn't support `signMessageV2` yet.

TronLink will support new version of tronWeb in `v3.28.x`.  You can use `adapter.signMessage` then.

Here is the [documentation of tronWeb](https://developers.tron.network/reference/signmessagev2).

**Comment by xyz27900** [comment]
Okay got it, thank you for your response
